 let questions = [
"In which part of your body would you find the cruciate ligament ?",
"What is the name of the main antagonist in the Shakespeare play Othello ?",
"What element is denoted by the chemical symbol Sn in the periodic table ?",
"What is the name of the 1976 film about the Watergate scandal, starring Robert Redford and Dustin Hoffman ?",
"How many of Henry VIII’s wives were called Catherine ?",
"What was the most popular girls name in the UK in 2019 ?",
"Which comedian was the second permanent host of Never Mind the Buzzcocks after Mark Lamarr ?",
"Which popular video game franchise has released games with the subtitles World At War and Black Ops ?",
"In what US State is the city Nashville ?",
"Which rock band was founded by Trent Reznor in 1988 ?",
"What is the currency of Denmark ?",
"Which Tennis Grand Slam is played on a clay surface ?",
"In which European country would you find the Rijksmuseum ?",
"How many films have Al Pacino and Robert De Niro appeared in together ?",
"What was the old name for a Snickers bar before it changed in 1990 ?",
"Who was the head of state in Japan during the second world war ?",
"What is the smallest planet in our solar system ?",
"Who wrote the novels Gone Girl and Sharp Objects ?",
"Which legendary surrealist artist is famous for painting melting clocks ?",
"Which football club plays its home games at Loftus Road",
"Continental United States has 4 time zones, can you name them ?",
"What was the Turkish city of Istanbul called before 1930 ?",
"From which US city do the band The Killers originate ?",
"Name the Coffee shop in US sitcom Friends",
"How many human players are there on each side in a polo match ?",
"In what year did Tony Blair become British Prime Minister ?",
"How many times has England won the men’s football World Cup ?",
"What is the capital of New Zealand?",
"Street artist Banksy is originally associated with which British city ?",
"From what grain is the Japanese spirit Sake made ?",
];

let responses = [
    "Knee",
    "Iago",
    "Tin",
    "All the President’s Men",
    3,
   " Olivia",
    "Simon Amstell",
    "Call of Duty",
    "Tennessee",
    "Nine Inch Nails",
    "Krone",
    "The French Open (Roland Garros)",
    "Netherlands",
    "Four",
    "Marathon",
    "Mercury",
    "Gillian Flynn",
    "Salvador Dali",
   " Queen’s Park Rangers",
   " Pacific, Mountain, Central, Eastern",
   " Constantinople",
    "Las Vegas",
    "Central Perk",
    "Four",
    1997,
    "Once (1966)",
    "Wellington",
    "Bristol",
    "Rice",

];

let wrongResponses = [
    "wrist",
    "Siré",
    "sodium",
    "Gone with the wind",
    2,
    "Brenda",
    "Daisy May",
    "Assassin's Creed",
    "Kansas",
    "Red hot chili peppers",
    "Franc",
    "Wimbledon",
    "Wales",
    "six",
    "Run",
    "Pluton",
    "Gill Flynn",
    "Salvador Bali",
   " Queen’s Fight Rangers",
   " North, South, East, west",
   " Istanbul",
    "Washington",
    "Central Park",
    "two",
    1995,
    "3 times",
    "Auckland",
    "Arsenal",
    "Corn",

];

let wrongResponses2 = [
    "head",
    "Lise",
    "aluminum",
    "Forest Gump",
    1,
   " Diana",
    "Phil Jupitus",
    "Soulcalibur",
    "Texas",
    "U2",
    "Euro",
    "US Open ",
    "Germany",
    "five",
    "Feet",
    "Jupiter",
    "Robert Flynn",
    "Henry Salvador",
   " Queen’s Power Rangers",
   " Pacific, Western, Central, Eastern",
   " Jerusalem",
    "Kansas",
    "Perk Central ",
    "Five",
    1998,
    "Twice",
    "Arllington",
    "Pristol",
    "wheat",

];
